# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

countries: ["US"]

enable:
  retrieve_databundle: true  #  Recommended 'true', for the first run. Otherwise data might be missing.
  retrieve_databundle_sector: true
  retrieve_cost_data: true  # true: retrieves cost data from technology data and saves in resources/costs.csv, false: uses cost data in data/costs.csv
  download_osm_data: true  # If 'true', OpenStreetMap data will be downloaded for the above given countries
  custom_busmap: false

  retrieve_cutout: false
  build_cutout: true

# retrieving precomputed files from Google Drive and bypassing re-execution
retrieve_precomputed:
  cutouts: false # if true, US cutouts are retrieved from Google Drive, else it is retrieved using retrieve_databundle_light if enable is true
  osm_raw: false # if true, bypasses download_osm_data rule
  osm_clean: false # if true, bypasses clean_osm_data rule
  shapes: false # if true, bypasses build_shapes rule
  osm_network: false # if true, bypasses build_osm_network rule
  base_network: false # if true, bypasses base_network rule
  renewable_profiles: false # if true, bypasses build_renewable_profiles rule

foresight: perfect

run:
  name: "US_2023_elec" # use this to keep track of runs with different settings

scenario:
  simpl: ['']
  ll: ['v1']
  clusters: [100]
  opts: [Co2L-3h]
  planning_horizons:
  - 2023
  sopts:
  - "3h"

electricity:
  extendable_carriers:
    Generator: []
    Store: []

  powerplants_filter: (DateOut >= 2023 or DateOut != DateOut) and (DateIn <= 2023 or DateIn != DateIn)
  custom_powerplants: replace # "false" use only powerplantmatching (ppm) data, "merge" combines ppm and custom powerplants, "replace" use only custom powerplants

renewable:
  hydro:
    normalization:
      method: eia
    hydro_capital_cost: true

co2:
  limit: 1.565e+9     # base * 1.1 for calibration purposes
  base: 1.490e+9      # power sector emissions US 2023 https://www.iea.org/countries/united-states/electricity
  emission_price: 0. # [currency/tCO2]; active via Ep wildcard

costs:
  year: 2020
  lifetime:
    CCGT: 45
    OCGT: 45
  efficiency:
    coal: 0.3195 # EIA https://www.eia.gov/electricity/annual/html/epa_08_01.html
    oil: 0.3005 # EIA https://www.eia.gov/electricity/annual/html/epa_08_01.html
    CCGT: 0.4429 # EIA https://www.eia.gov/electricity/annual/html/epa_08_01.html
    nuclear: 0.3254 # EIA https://www.eia.gov/electricity/annual/html/epa_08_01.html
    biomass: 0.30 # EIA https://www.eia.gov/electricity/annual/html/epa_08_01.html
  VOM:
    oil: 100.0
